package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/vaarde/mise/internal/provider"
)

// GroupAll is the location group every fetched workspace has: it matches
// every location on the account.
const GroupAll = "${group.all}"

// LocationsFileName holds the account's locations as reference data.
const LocationsFileName = "locations.yaml"

// DefaultFileLayout maps a resource type to the file fetch writes it to.
// Grouping by concept rather than dumping one giant file is what makes
// the result reviewable in a pull request.
var DefaultFileLayout = map[string]string{
	"square_catalog_tax":           "taxes.yaml",
	"square_catalog_discount":      "discounts.yaml",
	"square_catalog_category":      filepath.Join("menu", "categories.yaml"),
	"square_catalog_item":          filepath.Join("menu", "items.yaml"),
	"square_catalog_modifier_list": filepath.Join("menu", "modifiers.yaml"),
}

// preferredPropertyOrder lists property keys that read better at the top
// of a block. Everything else is emitted alphabetically, which keeps
// output stable so re-running fetch produces no spurious diff.
var preferredPropertyOrder = []string{"name", "description", "percentage", "enabled"}

// fileHeader explains where a generated file came from.
const fileHeader = `# Generated by mise fetch from your live POS configuration.
#
# This is your configuration now — edit it, commit it, review changes in
# pull requests. Running 'mise fetch' again overwrites these files.
`

// locationsFileHeader marks locations.yaml as read-only reference data.
const locationsFileHeader = `# Generated by mise fetch.
#
# Locations are created in your POS dashboard, not by Mise. This file is
# reference data: it tells you which IDs the location groups in mise.yaml
# and the 'locations:' fields in your resource files refer to.
`

// FileFor returns the file a resource type belongs in, falling back to
// one file per type for platforms not yet in the layout.
func FileFor(resourceType string) string {
	if path, ok := DefaultFileLayout[resourceType]; ok {
		return path
	}
	return resourceType + ".yaml"
}

// GenerateResourceFiles writes resource definitions into the workspace,
// grouped by type. It returns the relative paths it wrote, sorted.
func GenerateResourceFiles(workDir string, resources []ResourceDef) ([]string, error) {
	byFile := map[string][]ResourceDef{}
	for _, res := range resources {
		path := FileFor(res.Type)
		byFile[path] = append(byFile[path], res)
	}

	written := make([]string, 0, len(byFile))
	for path, defs := range byFile {
		// Sort within a file so the output does not depend on map or
		// goroutine ordering.
		sort.Slice(defs, func(i, j int) bool {
			if defs[i].Type != defs[j].Type {
				return defs[i].Type < defs[j].Type
			}
			return defs[i].Name < defs[j].Name
		})

		if err := writeResourceFile(filepath.Join(workDir, path), defs); err != nil {
			return nil, err
		}
		written = append(written, filepath.ToSlash(path))
	}

	sort.Strings(written)
	return written, nil
}

// writeResourceFile renders one resource YAML file.
func writeResourceFile(path string, defs []ResourceDef) error {
	root := &yaml.Node{Kind: yaml.MappingNode}

	items := &yaml.Node{Kind: yaml.SequenceNode}
	for _, def := range defs {
		node, err := resourceNode(def)
		if err != nil {
			return fmt.Errorf("cannot render %s: %w", def.FullName(), err)
		}
		items.Content = append(items.Content, node)
	}

	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "resources"},
		items,
	)

	return writeYAMLFile(path, fileHeader, root)
}

// resourceNode renders one resource with its keys in a readable order:
// what it is, what it is called, where it applies, then its properties.
func resourceNode(def ResourceDef) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode}

	addScalar(node, "type", def.Type)
	addScalar(node, "name", def.Name)

	if def.Locations != nil {
		value := &yaml.Node{}
		if err := value.Encode(def.Locations); err != nil {
			return nil, err
		}
		// Explicit location lists are far easier to scan on one line
		// than as a bullet per ID.
		if value.Kind == yaml.SequenceNode {
			value.Style = yaml.FlowStyle
		}
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "locations"}, value)
	}

	props, err := propertiesNode(def.Properties)
	if err != nil {
		return nil, err
	}
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "properties"}, props)

	return node, nil
}

// propertiesNode renders a property map with the most useful keys first.
func propertiesNode(props map[string]interface{}) (*yaml.Node, error) {
	node := &yaml.Node{Kind: yaml.MappingNode}

	for _, key := range orderedKeys(props) {
		value := &yaml.Node{}
		if err := value.Encode(props[key]); err != nil {
			return nil, fmt.Errorf("cannot render property %q: %w", key, err)
		}
		node.Content = append(node.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: key}, value)
	}

	return node, nil
}

// orderedKeys returns preferred keys first, then the rest alphabetically.
func orderedKeys(props map[string]interface{}) []string {
	remaining := make(map[string]bool, len(props))
	for key := range props {
		remaining[key] = true
	}

	ordered := make([]string, 0, len(props))
	for _, key := range preferredPropertyOrder {
		if remaining[key] {
			ordered = append(ordered, key)
			delete(remaining, key)
		}
	}

	rest := make([]string, 0, len(remaining))
	for key := range remaining {
		rest = append(rest, key)
	}
	sort.Strings(rest)

	return append(ordered, rest...)
}

// GenerateLocationsFile writes locations.yaml.
func GenerateLocationsFile(workDir string, locations []provider.Location) (string, error) {
	sorted := append([]provider.Location(nil), locations...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].Name != sorted[j].Name {
			return sorted[i].Name < sorted[j].Name
		}
		return sorted[i].ID < sorted[j].ID
	})

	items := &yaml.Node{Kind: yaml.SequenceNode}
	for _, l := range sorted {
		entry := &yaml.Node{Kind: yaml.MappingNode}
		addScalar(entry, "id", l.ID)
		addScalar(entry, "name", l.Name)
		addScalarIfSet(entry, "state", l.State)
		addScalarIfSet(entry, "city", l.Metadata["city"])
		addScalarIfSet(entry, "timezone", l.Timezone)
		addScalarIfSet(entry, "address", l.Address)
		addScalarIfSet(entry, "status", l.Metadata["status"])
		items.Content = append(items.Content, entry)
	}

	root := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "locations"},
		items,
	)

	path := filepath.Join(workDir, LocationsFileName)
	if err := writeYAMLFile(path, locationsFileHeader, root); err != nil {
		return "", err
	}
	return LocationsFileName, nil
}

// writeYAMLFile renders a node to disk under a comment header.
func writeYAMLFile(path, header string, root *yaml.Node) error {
	if dir := filepath.Dir(path); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("cannot create directory for %s: %w", path, err)
		}
	}

	var buf strings.Builder
	buf.WriteString(header)
	buf.WriteString("\n")

	encoder := yaml.NewEncoder(&buf)
	encoder.SetIndent(2)
	if err := encoder.Encode(root); err != nil {
		return fmt.Errorf("cannot encode %s: %w", path, err)
	}
	if err := encoder.Close(); err != nil {
		return fmt.Errorf("cannot encode %s: %w", path, err)
	}

	if err := os.WriteFile(path, []byte(buf.String()), 0o644); err != nil {
		return fmt.Errorf("cannot write %s: %w", path, err)
	}
	return nil
}

func addScalar(node *yaml.Node, key, value string) {
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value},
	)
}

func addScalarIfSet(node *yaml.Node, key, value string) {
	if strings.TrimSpace(value) != "" {
		addScalar(node, key, value)
	}
}

// ExistingGeneratedFiles reports which of the files a fetch would write
// already exist, so the CLI can warn before overwriting hand edits.
func ExistingGeneratedFiles(workDir string, resourceTypes []string) []string {
	candidates := map[string]bool{LocationsFileName: true}
	for _, t := range resourceTypes {
		candidates[FileFor(t)] = true
	}

	existing := make([]string, 0, len(candidates))
	for path := range candidates {
		if info, err := os.Stat(filepath.Join(workDir, path)); err == nil && !info.IsDir() {
			existing = append(existing, filepath.ToSlash(path))
		}
	}

	sort.Strings(existing)
	return existing
}
